### Linear Algebra for CpE
## Laboratory 6 : Matrices
<br>Coded and submitted by:
<br><i>ANGELO, Jamaica Joy S.
<br>58010

Now that you have a fundamental knowledge about vector representations, we'll try to look into greater dimensions.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.

# Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

Let's say for example you have $A$ and $B$ as system of equation.

$$
A = \left\{
    \begin{array}\\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. $$

We could see that $A$ is a system of 2 equations with 2 parameters. While $B$ is a system of 3 equations with 3 parameters. We can represent them as matrices as:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}
$$

So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed in doing them in here in Python.

### Declaring Matrices

Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas $A$ is a matrix consisting of elements denoted by $a_{i,j}$. Denoted by $i$ is the number of rows in the matrix while $j$ stands for the number of columns.<br>
Do note that the $size$ of a matrix is $i\times j$.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using <b>shape</b>, <b>dimensions</b> and <b>size</b> attributes, we'll use them to analyze these matrices.

In [1]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [3]:
## Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [5]:
G = np.array([
    [1,1],
    [2,2]
])
describe_mat(G)

Matrix:
[[1 1]
 [2 2]]

Shape:	(2, 2)
Rank:	2



In [6]:
## Declaring a 3 x 2 matrix
B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [8]:
H = np.array([1,2,3,4,5])
describe_mat(H)

Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



## Categorizing Matrices

There are several ways of classifying matrices. Once could be according to their <b>shape</b> and another is according to their <b>element values</b>. We'll try to go through them.

### According to shape

#### Row and Column Matrices

Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be $1 \times j$ and column matrices would be $i \times 1$.

In [10]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    1, 3, 2
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 3 2]

Shape:	(3,)
Rank:	1

Matrix:
[[1 2 3]]

Shape:	(1, 3)
Rank:	2



In [11]:
## Declaring a Column Matrix

col_mat = np.array([
    [1],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



#### Square Matrices

Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if $i = j$. We can tweak our matrix descriptor function to determine square matrices.

In [8]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [22]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square: False



### According to element values

#### Null Matrix

A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [9]:
def mat_desc(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [26]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


#### Zero Matrix

A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [28]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


#### Ones Matrix

A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [34]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### Diagonal Matrix

A diagonal matrix is a square matrix that has values only at the diagonal of the matrix. 

In [24]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [32]:
d = np.diag([2,3,5,7])
np.diag(d).shape == d.shape[0] == d.shape[1]


array([2, 3, 5, 7])

#### Identity Matrix

An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [34]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Upper Triangular Matrix

An upper triangular matrix is a matrix that has no values below the diagonal. 

In [36]:
np.array([
    [1,2,3],
    [0,3,1],
    [0,0,5]
])

array([[1, 2, 3],
       [0, 3, 1],
       [0, 0, 5]])

#### Lower Triangular Matrix

A lower triangular matrix is a matrix that has no values above the diagonal.

In [37]:
np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]
])

array([[1, 0, 0],
       [5, 3, 0],
       [7, 8, 5]])

## Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.

$$\theta = 5x + 3y - z$$

In [38]:
theta = np.array([
              [5,3,-1],
])
describe_mat(theta)

Matrix:
[[ 5  3 -1]]

Shape:	(1, 3)
Rank:	2
Is Square: False



2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

In [39]:
number2_mat = np.array([
             [1,2,1],
             [0,4,-1],
             [0,0,10]
])
describe_mat(number2_mat)

Matrix:
[[ 1  2  1]
 [ 0  4 -1]
 [ 0  0 10]]

Shape:	(3, 3)
Rank:	2
Is Square: True



3. Given the matrix below, express it as a linear combination in a markdown.

In [41]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


$$G = 
\begin{bmatrix}1&7&8\\2&2&2\\4&6&7
\end{bmatrix}$$

$$G=\left\{\begin{array} 1g_1+7g_2+8g_3 \\2g_1+2g_2+2g_3\\4g_1+6g_2+7g_3
\end{array}\right.$$

4. Given the matrix below, display the output as a LaTeX makdown also express it as a system of linear combinations.

In [42]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

$$
H = \left\{\begin{array}
1x_1\\
2x_1+ 2y_2\\
4x_1+ 6y_2 +7z_3
\end{array}\right.
$$

$$\begin{equation*}
H = 
\begin{bmatrix}
1 & 0 & 0 \\
2 & 2 & 0 \\
4 & 6 & 7
\end{bmatrix}
\end{equation*}$$

# Matrix Algebra

### Addition

In [48]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
    [2,2],
    [0,0],
    [1,1]
])
A+B

array([[3, 4],
       [2, 3],
       [5, 2]])

In [54]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[3, 4],
       [4, 5],
       [6, 3]])

### Subtraction

In [49]:
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [59]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

### Element-wise Multiplication

In [67]:
A*B
np.multiply(A,B)

array([[2, 4],
       [0, 0],
       [4, 1]])

In [60]:
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

In [64]:
alpha=10**-10
A/(alpha+B)

array([[5.e-01, 1.e+00],
       [2.e+10, 3.e+10],
       [4.e+00, 1.e+00]])

In [66]:
np.add(A,B)

array([[3, 4],
       [2, 3],
       [5, 2]])

## Activity

### Task 1

Create a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

### FUNCTION AREA:

In [2]:
class bcolors: #just to add colors.
    FAIL = '\033[91m'
    ENDC = '\033[0m'
def mat_desc(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False
        print(f'SHAPE: \t\t{matrix.shape}\nSIZE:\t\t{matrix.size}\nRANK:\t\t{matrix.ndim}\nIS SQUARE:\t{is_square}')
        if np.all(matrix == np.eye(matrix.shape[0], matrix.shape[1])):
            identity = np.eye(matrix.shape[0], matrix.shape[1])
            print(f'\nIDENTITY MATRIX: \n{identity}')
        elif np.all(matrix == np.ones((matrix.shape))):
            ones = np.ones((matrix.shape))
            print(f'\nONES MATRIX: \n{ones}')
        elif np.all(matrix == np.zeros((matrix.shape))):
            zero = np.zeros((matrix.shape))
            print(f'\nZEROS MATRIX: \n{zero}')
        else:
            print(f'\nMATRIX IS SCALAR \n{matrix}')
    else:
        #print('\nTHE MATRIX IS EMPTY!')
        print(bcolors.FAIL + '\nTHE MATRIX IS EMPTY!' + bcolors.ENDC)

## SAMPLE MATRICES:

## 1.

In [6]:
A = np.array([
             [1, 0, 0, 0],
             [0, 1, 0, 0],
             [0, 0, 1, 0],
             [0, 0, 0, 1]
])
mat_desc(A)
#print(f'\nIDENTITY MATRIX: \n{np.eye(3)}')
#is_empty = A.size == 0 # DETERMINES IF THE MATRIX IS EMPTY
#print('\nEMPTY MATRIX: ', is_empty)
          #   [8,4,2],
           #  [3,-4,-6],
           #  [-5,7,2]

SHAPE: 		(4, 4)
SIZE:		16
RANK:		2
IS SQUARE:	True

IDENTITY MATRIX: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 2.

In [12]:
theta = np.array([
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0]
])
mat_desc(theta)

theta = np.array([])
mat_desc(theta)

SHAPE: 		(5, 5)
SIZE:		25
RANK:		2
IS SQUARE:	True

ZEROS MATRIX: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

THE MATRIX IS EMPTY!


## 3.

In [8]:
gamma = np.array([
            [1, 1, 1],
            [1, 1, 1],
            [1, 1, 1],
            [1, 1, 1]
])
mat_desc(gamma)

SHAPE: 		(4, 3)
SIZE:		12
RANK:		2
IS SQUARE:	False

ONES MATRIX: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 4.

In [25]:
phi = np.array([
            [0, 0, 1],
            [1, 0, 1],
            [1, 0, 0]
])
mat_desc(phi)

SHAPE: 		(3, 3)
SIZE:		9
RANK:		2
IS SQUARE:	True

MATRIX IS SCALAR 
[[0 0 1]
 [1 0 1]
 [1 0 0]]


## 5.

In [36]:
omega = np.array([
            [0, 1, 0],
            [1, 0, 1],
            [1, 1, 0],
            [0, 1, 1]
])
mat_desc(omega)

SHAPE: 		(4, 3)
SIZE:		12
RANK:		2
IS SQUARE:	False

MATRIX IS SCALAR 
[[0 1 0]
 [1 0 1]
 [1 1 0]
 [0 1 1]]


### FLOWCHART:

<img src = "img/lab6task1flowchart.jpeg" width = 600 align = "center"/>

### DISCUSSION:

On the first task, we are asked to create a function named `def mat_desc()` that thoroughly describes a matrix. It should display the shape, rank, and size of the matrix, whether it is square or a non-square, if the matrix is an empty matrix, and if the matrix is an identity ones, or a zeros matrix. I used 5 different sample matrices that are not lower than (3,3). `class bcolors` was used to add some colors on the output so that it would not look so dull. The `FAIL` as the color red and `ENDC` to terminate. `def mat_desc()` was used since we are asked to define the function as it is. Then, the condition `if matrix.size > 0` is used to determine if the matrix is a null matrix. A null matrix is basically a matrix that has no elements. The condition `is_square` is used to determine if the matrix would be square or not. It will then print the following words to identify its size, shape, rank, and if it is square. The condition is set to else if if the matrix is empty and will print `THE MATRIX IS EMPTY!` In colour red. Then, another condition is set  to identify if the matrix will be an identity matrix. An identity matrix is a special diagonal matrix wherein the values of the array in matrix form are ones. In the first sample matrix, the array’s shape is (4,4), its size is 16, its rank is 2, and it is definitely square. 

Then, an `elif` condition is set to determine if the sample matrix is not an identity matrix, then, it would be a ones matrix. Basically, a ones matrix is any rectangular matrix with all of the elements inside are ones (1s). gamma is set to a ones matrix with its shape as (4,3), its size is 12, its rank is 2 and it is not a square since its shape does not meet a square. 

As for the zeros matrix, the condition is set to another `elif` statement in order to determine whether it is a zero matrix or not. A zero matrix is just like a ones matrix but instead one ones (1s) as its elements, it would be zeros (0s). The sample matrix # 2 is basically a zero matrix. Its shape is (5,5), size is 25, its rank is 2, and it is definitely a square. However, it is an empty matrix because it’s a zero matrix and having a zero matrix is basically the same as having none or an empty one. It also satisfies the condition in which it determines if the matrix is empty.

As for the last part, the condition is an `else` statement because if the above conditions `(elif statements)` are not met by the matrix, then, it would be determined as a scalar matrix. In sample matrix numbers 4 and 5, their shape are (3,3) and (4,3), size are 9 and 12, ranks are both 2, sample matrix # 4 is a square but # 5 is not. They are both scalar since they <b>do not satisfy</b> the conditions that are stated in the `elif` statements.

### Task 2

Create a function named `mat_operations()` that takes in two matrices or scalars a input parameters it should:<br>
 1. Display the description of each matrix, if the parameter is a scalar it tells that it is a scalar rather than describing it as a matrix.
 2. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 3. Returns the sum of the matrices.
 4. Returns the differen of the matrices.
 5. Returns the element-wise multiplication of the matrices.
 6. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

### FUNCTION AREA:

In [13]:
class bcolors: #these codes are just to add extra colours to the output.
    FAIL = '\033[91m'
    ENDC = '\033[0m'
def mat_operations(matrix1, matrix2):
    a = 10**-10 #for quotient
    if(matrix1.shape == matrix2.shape):
            print("\nTHIS IS A MATRIX.")
            sum = matrix1 + matrix2
            print(f'\nSUM:\n{sum}')
            
            difference = matrix1 - matrix2
            print(f'\nDIIFFERENCE:\n{difference}')
            
            product = matrix1 * matrix2
            print(f'\nPRODUCT:\n{product}')
            
            quotient = matrix1 // matrix2 + a
            print(f'\nQUOTIENT:\n{quotient}')
            
    elif(matrix1.ndim & matrix2.ndim) == 0:
            print("THIS IS A SCALAR.")
            print(bcolors.FAIL + "THE MATRICES ARE NOT VIABLE FOR OPERATIONS BECAUSE IT IS NOT IN A RECTANGLE NOR A SQUARE ARRAY OF NUMBERS" + bcolors.ENDC)
        

### EXAMPLES:

## 1.

In [9]:
beta = np.array([
            [12,-8,10],
            [4,-3,2],
            [-7,2,1]
])
eta = np.array([
            [9,-18,4],
            [9,8,3],
            [1,2,3]
])
mat_operations(beta,eta)


THIS IS A MATRIX.

SUM:
[[ 21 -26  14]
 [ 13   5   5]
 [ -6   4   4]]

DIIFFERENCE:
[[  3  10   6]
 [ -5 -11  -1]
 [ -8   0  -2]]

PRODUCT:
[[108 144  40]
 [ 36 -24   6]
 [ -7   4   3]]

QUOTIENT:
[[ 1.e+00  1.e-10  2.e+00]
 [ 1.e-10 -1.e+00  1.e-10]
 [-7.e+00  1.e+00  1.e-10]]


## 2.

In [12]:
omega = np.array([
            [4,-3,6],
            [7,9,9],
            [4,1,2,9] # this is not a matrix because it is not in a rectangular nor a square array of numbers.
])
kappa = np.array([
            [9,2,1],
            [3,6,9],
            [1,-5,3]
])
mat_operations(omega,kappa)

THIS IS A SCALAR.
THE MATRICES ARE NOT VIABLE FOR OPERATIONS BECAUSE IT IS NOT IN A RECTANGLE NOR A SQUARE ARRAY OF NUMBERS


## 3.

In [51]:
delta = np.array([
            [3,-9,-7],
            [16,28,11],
            [9,4,-3] # this is not a matrix because it is not in a rectangular nor a square array of numbers.
])
nu = np.array([
            [1,22,17],
            [2,2,14],
            [7,-13,-5]
])
mat_operations(delta,nu)


THIS IS A MATRIX.

SUM:
[[ 4 13 10]
 [18 30 25]
 [16 -9 -8]]

DIIFFERENCE:
[[  2 -31 -24]
 [ 14  26  -3]
 [  2  17   2]]

PRODUCT:
[[   3 -198 -119]
 [  32   56  154]
 [  63  -52   15]]

QUOTIENT:
[[ 3.0e+00 -1.0e+00 -1.0e+00]
 [ 8.0e+00  1.4e+01  1.0e-10]
 [ 1.0e+00 -1.0e+00  1.0e-10]]


## 4.

In [52]:
delta = np.array([
            [1,-4,-9],
            [12,24,7],
            [8,3,-10] # this is not a matrix because it is not in a rectangular nor a square array of numbers.
])
nu = np.array([
            [9,18,27],
            [4,3,1],
            [7,9,-2]
])
mat_operations(delta,nu)


THIS IS A MATRIX.

SUM:
[[ 10  14  18]
 [ 16  27   8]
 [ 15  12 -12]]

DIIFFERENCE:
[[ -8 -22 -36]
 [  8  21   6]
 [  1  -6  -8]]

PRODUCT:
[[   9  -72 -243]
 [  48   72    7]
 [  56   27   20]]

QUOTIENT:
[[ 1.e-10 -1.e+00 -1.e+00]
 [ 3.e+00  8.e+00  7.e+00]
 [ 1.e+00  1.e-10  5.e+00]]


## 5.

In [53]:
Q = np.array([
            [7,14,-26],
            [3,-8,7],
            [8,9,-5] # this is not a matrix because it is not in a rectangular nor a square array of numbers.
])
R = np.array([
            [1,6,4],
            [3,-5,-7,9],
            [2,4,6]
])
mat_operations(Q,R)

THIS IS A SCALAR.
THE MATRICES ARE NOT VIABLE FOR OPERATIONS BECAUSE IT IS NOT IN A RECTANGLE NOR A SQUARE ARRAY OF NUMBERS


### FLOWCHART:

<img src = "img/lab6task2flowchart.jpeg" width = 600 align = "center"/>

### DISCUSSION: 

As for Task 2, we are tasked to create a function names `mat_operations()` that takes two matrices or scalars. It should display the description of each matrix, if the parameter is a scalar it tells that it is a scalar rather than describing it as a matrix, determines if the matrices are viable for operation and returns your own error message if they are not viable, and returns the sum, difference, product, or quotient of the matrices. The sample should also not be lower than (3,3). The `class bcolors` was again used to add some colors on the output so that it would not look so dull. The `FAIL` as the color red and `ENDC` to terminate. 

`def mat_operations()` is used in order to define the operations that are going to be used in the task. `a = 10**-10` is used to define the formula that is going to be used in order to get the quotient of the sample. `if(matrix1.shape == matrix2.shape)` is used to determine if the sample matrices’ shapes were equal, then it will be a matrix. It will then proceed to calculate the solution/ answers using the different operations stated in the function area. Sum for adding, difference for subtracting, product for multiplying, and quotient for dividing the sample matrices and it will then print their output accordingly.

However if the matrix is a scalar, their ranks would not be then equal to each other and `elif(matrix1.ndim & matrix2.ndim) == 0` is used. It will then print `“THIS IS SCALAR”` and underneath it is another message with a red coloured text saying `“THE MATRICES ARE NOT VIABLE FOR OPERATIONS BECAUSE IT IS NOT IN A RECTANGLE NOR A SQUARE ARRAY OF NUMBERS”`. It will not be solved using an operation because the other spaces are empty making it not viable to be added, multiplied, subtracted or divided.

## Conclusion

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "how can matrix operations solve problems in agriculture?".